### ISSUE TITLE
关于模型加速的一些想法

### ISSUE THREAD

**Issue by Egrt** [Tau-J/rtmlib#1]
请问，能否让目标检测模型det和姿态检测rtmpose共用一个backbone，将检测器的回归头和simcchead分别解耦，这样能否加快推理速度？

**Comment by Tau-J** [comment]
@Egrt 对于topdown模型而言，答案是不能，具体原因可以了解一下topdown范式是如何推理的。其他的bottomup或者one-stage模型，可能思想上比较接近于你所说的。

**Comment by Egrt** [comment]
> @Egrt 对于topdown模型而言，答案是不能，具体原因可以了解一下topdown范式是如何推理的。其他的bottomup或者one-stage模型，可能思想上比较接近于你所说的。

感谢您的解答！
