### ISSUE TITLE
How specify target cuda device? 

### ISSUE THREAD

**Issue by tszhang97** [Tau-J/rtmlib#10]
![image](https://github.com/Tau-J/rtmlib/assets/39046939/44c1e38c-0052-470c-9303-8807e56ba410)
I'm using onnx gpu backend and want to set cuda:2 device. It seems that I could not select cuda device.

**Comment by Tau-J** [comment]
Hi @tszhang97 , thanks for using rtmlib. The easiest way is to set the visible device, e.g. `CUDA_VISIBLE_DEVICES=gpu_ids python3 xxx.py`

**Comment by tszhang97** [comment]
I know this operation, however I'm using rtmlib as a submodule of a large project. Maybe we can add provider_options like this:
  provider_options = [{"device_id": device_id}]
  self.session = ort.InferenceSession(path_or_bytes=onnx_model,
                                                providers=[providers],
                                                provider_options=provider_options)

**Comment by tszhang97** [comment]
Additional operation to get device_id and add provider_options works for me.

**Comment by Tau-J** [comment]
> Additional operation to get device_id and add provider_options works for me.

Hi @tszhang97 , would you like to raise a PR to this repo? Any contribution is much appreciated.

**Comment by edwardnguyen1705** [comment]
Dear @Tau-J ,

Would it be possible to support specifying GPU ID like this https://github.com/cap-ntu/ML-Model-CI/issues/37?

**Comment by edwardnguyen1705** [comment]
Hi @Tau-J ,
Please check this PR: https://github.com/Tau-J/rtmlib/pull/44
