### ISSUE TITLE
使用rtmdet推理结果不对

### ISSUE THREAD

**Issue by t-x-l** [Tau-J/rtmlib#2]
你好，我下载了mmdetection中的rtmdet-tiny模型，以及自己训练出来的rtmdet-tiny模型，转成onnx后，使用rtmlib推理出的结果总是不对。yolox的是对的。请问是哪里的问题呢？
![微信图片_20231106135523](https://github.com/Tau-J/rtmlib/assets/21121283/e8bc4d6a-8cbe-4dcc-95ec-0edbab6ecca9)

**Comment by t-x-l** [comment]
跑了hand的例子，里面调用了rtmdet_nano的那个模型，预测好像也是不对的。

**Comment by t-x-l** [comment]
rtmdet输入的图像需要归一化。

**Comment by Tau-J** [comment]
> rtmdet输入的图像需要归一化。

谢谢你的反馈，请问你愿意提一个 PR 来修复一下这个问题么？

**Comment by t-x-l** [comment]
好的
