### ISSUE TITLE
Inference time same as in MMPose? All OS supported?

### ISSUE THREAD

**Issue by davidpagnon** [Tau-J/rtmlib#23]
Ho, 
Thank you for releasing such a useful library!
I want to include pose estimation within my [Pose2Sim](https://github.com/perfanalytics/pose2sim) toolbox, and I was just about to make the user install MMPose, but @hunminkim98 told me about that repo. Something light and easy to install would be even better.
But I'm wondering about two things:
- is inference time the same as when you run MMPose?
- can you run rtmlib on any OS? (Within python)

Thanks in advance !

**Comment by Tau-J** [comment]
Hi @davidpagnon , MMPose is based on pytorch while rtmlib can inference on various backend like onnxruntime, openvino, etc. Due to pytorch is not a framework focused on inference, the inference speed of rtmlib would be higher. As for OS, win/macOS/Linux are supported.

**Comment by davidpagnon** [comment]
It makes sense! Thank you for your answer.
