### ISSUE TITLE
Upload latest commits to pypi

### ISSUE THREAD

**Issue by davidpagnon** [Tau-J/rtmlib#27]
Hi, 
Not exactly an issue, but is there any chance you could release the latest RTMLib commits on Pypi? This would allow me to release my package as well, with yours as a dependency.

**Comment by Tau-J** [comment]
Hi @davidpagnon , I just uploaded latest version to Pypi. Enjoy~

**Comment by davidpagnon** [comment]
Awesome!
I've got to thank you again for this library, it's going to make everything much easier and more straightforward for [Pose2Sim](https://github.com/perfanalytics/pose2sim) users :)
