### ISSUE TITLE
About bounding box (minimal tight bbx?)

### ISSUE THREAD

**Issue by zehongs** [Tau-J/rtmlib#30]
Thanks for the great work! This library is incredibly clean compared to mmpose.

I have a question about the definition of the bounding box. It doesn’t always appear to be the minimal bounding box like in YoloV8. Is there a specific interpretation or convention regarding the size of the bounding box? I would appreciate any clarification from the author.

I've attached two images as examples.
<img width="970" alt="image" src="https://github.com/user-attachments/assets/a50978cc-d3dc-49a3-acb9-92b4005f39f7">

**Comment by Tau-J** [comment]
Hi @zehongs , as a convention, we will expand the minimal bbox (usually calculated via keypoints) with a factor 0.25 to ensure the whole instance is inside the bbox.

**Comment by zehongs** [comment]
Hi, thanks for the reply!
Actually, this is a minor quesetion: Do you have any comments on the bounding boxes I show in the examples? They are the outputs (xyxy-format) of the rtmdet (https://download.openmmlab.com/mmpose/v1/projects/rtmposev1/onnx_sdk/yolox_m_8xb8-300e_humanart-c2c7a14a.zip). It's clear that they have different bahavoirs, i.e. left=minimal tight, right=somewhat expanded.

I'm not sure if this comes from some algorithm in the onnx model, or this is related to bounding box annotation in the training data.

**Comment by Tau-J** [comment]
I'm sure there is no such kind of processing in onnx model. The expansion only happens during the input stage of pose estimation.(For mmpose, the bbox annotations will be expanded in the [augmentation pipeline](https://github.com/open-mmlab/mmpose/blob/b9c1b54fbe7f9bddd90206946b239dc440b0cf50/mmpose/datasets/transforms/common_transforms.py#L77)). So, if the bbox you show is directly from onnx model of detection, I think it is just a model performance issue. (TBH, I think even the right one is good enough in most circumstances.)

**Comment by zehongs** [comment]
I see. Thank you!
