### ISSUE TITLE
请问这样的资源占用情况是正常的吗，如何优化可以减少资源占用，可以达到mediapipe那样10%以下吗

### ISSUE THREAD

**Issue by zzb181** [Tau-J/rtmlib#35]
<img width="1221" alt="企业微信截图_17254141849505" src="https://github.com/user-attachments/assets/762b4aa4-86f3-4f9c-855c-b2c15a8ef98e">
`import time

import cv2

from rtmlib import PoseTracker, Body, draw_skeleton

INPUT_FILE = 'D:\\ai\\live_mocap-master\\videos\\3.mp4'
cap = cv2.VideoCapture(INPUT_FILE)

openpose_skeleton = False  # True for openpose-style, False for mmpose-style

pose_tracker = PoseTracker(
    Body,
    det_frequency=120,
    to_openpose=openpose_skeleton,
    tracking=False,  # True for tracking, False for detection only
    mode='balanced',  # balanced, performance, lightweight
    backend="onnxruntime",# opencv, onnxruntime, openvino
    device='cpu')

frame_idx = 0
start = time.time()
while cap.isOpened():
    success, frame = cap.read()
    frame_idx += 1
    if not success:
        break
    keypoints, scores = pose_tracker(frame)
   
    img_show = draw_skeleton(frame,
                             keypoints,
                             scores,
                             openpose_skeleton=openpose_skeleton,
                             line_width = 1
                            #  kpt_thr=4
                            #  kpt_thr=0.43
                             )

    end = time.time()
    fps = 1 / (end - start)
    start = end
    #实时显示帧数
    # image = cv2.flip(image, 1)
    cv2.putText(frame, "FPS {0}".format(int(fps)), (10, 50),
                cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 0, 255),2)  
    
    cv2.imshow('img', frame)
    if cv2.waitKey(1) & 0xFF == 27:
        break`

**Comment by Tau-J** [comment]
你好，看起来是正常的。资源占用问题我无法解答。
