### ISSUE TITLE
Issue Report: Low FPS with onnxruntime-gpu

### ISSUE THREAD

**Issue by LivingSparks10** [Tau-J/rtmlib#4]
### Description
I've installed the `rtmlib` library by following the "install from source code" instructions using `pip install onnxruntime-gpu`. I am using the `cuda` device and the `onnxruntime` backend. However, I am experiencing a maximum of 7 fps.

### System Information
- **onnxruntime-gpu Version:** 1.16.3
- **CUDA Availability:** Yes
  - **CUDA Version:** 11.8
- **cuDNN Availability:** Yes
  - **cuDNN Version:** 8700
- **nvcc (NVIDIA Cuda compiler) Version:** 11.8.89
- **GPU:** NVIDIA GeForce RTX 3080 Ti Laptop GPU
- **Operating System:** Windows 11

### Minimal Code to Reproduce
```python
import time
import cv2
from rtmlib import PoseTracker, Wholebody, draw_skeleton

device = 'cuda'
backend = 'onnxruntime'

cap = cv2.VideoCapture('./dance.mp4')
openpose_skeleton = False  # True for openpose-style, False for mmpose-style

wholebody = PoseTracker(
    Wholebody,
    det_frequency=20,
    to_openpose=openpose_skeleton,
    mode='lightweight',  # balanced, performance, lightweight
    backend=backend,
    device=device)

frame_idx = 0
start_time = time.time()
while cap.isOpened():
    success, frame = cap.read()

    if not success:
        break
    s = time.time()
    keypoints, scores = wholebody(frame)
    det_time = time.time() - s
    print('det: ', det_time)

    img_show = frame.copy()

    # if you want to use black background instead of original image,
    # img_show = np.zeros(img_show.shape, dtype=np.uint8)

    img_show = draw_skeleton(img_show,
                             keypoints,
                             scores,
                             openpose_skeleton=openpose_skeleton,
                             kpt_thr=0.43)
    frame_idx += 1

    img_show = cv2.resize(img_show, (960, 540))
    cv2.imshow('img', img_show)
    cv2.waitKey(1)

end_time = time.time()
elapsed_time = end_time - start_time
fps = frame_idx / elapsed_time
print('Average FPS: {:.2f}'.format(fps))
```

### Results
```
det:  0.048416852951049805
det:  0.04732680320739746
det:  0.043745994567871094
det:  0.05219006538391113
Average FPS: 6.73
```

### Expected Behavior
I expect to achieve a higher FPS considering the use of onnxruntime-gpu and the provided system specifications. Any guidance on optimizing the performance would be appreciated. Thanks!

**Comment by Tau-J** [comment]
Maybe you need to set your default gpu mode as performance mode. Or some warm-up can be helpful.
