### ISSUE TITLE
Strange confidence score for "performance" model

### ISSUE THREAD

**Issue by bonlime** [Tau-J/rtmlib#42]
Hi, thanks for a great project. I've tried using both "performance" and "balanced" models for pose detection and first one outputs confidence scores that are in a very strange range, most of them are in [1, 5+] range, not [0, 1] as I would expect. What the reason for this? can this be fixed?

**Comment by Tau-J** [comment]
Hi @bonlime . We have not imposed any restrictions on the range of the score output in our algorithm design, so it will not be a result that takes values between 0 and 1. If necessary, you can normalize it and determine a reasonable threshold through a certain number of tests on images in your own application scenarios.

**Comment by bonlime** [comment]
isn't it strange to not impose any range? shouldn't it be a "probability" score of some sort?
