### ISSUE TITLE
Can you provide a version that will run on windows?

### ISSUE THREAD

**Issue by Yangxinyee** [Tau-J/rtmlib#5]

**Comment by Yangxinyee** [comment]
This is a very good repository! I love it, but I can't run it on a Linux system for the time being. The problem with running on windows appears in the model file download section. Or can you tell me how to modify it to run on Windows?

**Comment by Yangxinyee** [comment]
When I ran rtm_demo.py, error is:

> Traceback (most recent call last):
>   File "D:\#MMICU\rtmlib\rtmo_demo.py", line 16, in <module>
>     body = Body(
>   File "D:\#MMICU\rtmlib\rtmlib\tools\solution\body.py", line 109, in __init__
>     self.pose_model = RTMO(pose,
>   File "D:\#MMICU\rtmlib\rtmlib\tools\pose_estimation\rtmo.py", line 20, in __init__
>     super().__init__(onnx_model, model_input_size, mean, std, backend,
>   File "D:\#MMICU\rtmlib\rtmlib\tools\base.py", line 35, in __init__
>     onnx_model = download_checkpoint(onnx_model)
>   File "D:\#MMICU\rtmlib\rtmlib\tools\file.py", line 146, in download_checkpoint
>     os.system(f'move {cached_onnx} {onnx_name}')
> **UnboundLocalError: local variable 'cached_onnx' referenced before assignment**

**Comment by Tau-J** [comment]
Hi @Yangxinyee , rtmlib only support bash terminal on Windows. Maybe you can install a bash terminal(e.g. git bash) and try again.
