### ISSUE TITLE
rtmo推理不正确

### ISSUE THREAD

**Issue by t-x-l** [Tau-J/rtmlib#6]
rtmo.py： 前处理部分应该去掉对图像的归一化；base.py：rtmo的openvino推理时候，好像不应该判断output0.ndim==ouput1.ndim

**Comment by Tau-J** [comment]
@t-x-l 非常感谢你的反馈，我修复了归一化的问题。openvino 暂时没有环境测试，请问你是否愿意提一个 PR 进行修复？

**Comment by Tau-J** [comment]
已修复。
