### ISSUE TITLE
How could I also get the detection bounding boxes from RTMO models?

### ISSUE THREAD

**Issue by n3ry7ve** [Tau-J/rtmlib#8]
Basically the title. WHat would i need to alter in the rtmlib/tools/pose_estimation/rtmpose.py code?

**Comment by Tau-J** [comment]
Hi @n3ry7ve , thanks for using rtmlib. Since RTMO is a one-stage algorithm, the model does not predict bounding boxes specifically. However, you can still obtain an approximate bounding box by calculating the maximum and minimum x and y values from a set of predicted keypoints.
